In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("D:\\newproject\\New folder\\Barley.data.csv")

In [3]:
#Na Handling
df.isnull().values.any()

False

In [4]:
df=df.dropna()

In [5]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
X = df.drop(['Predictor'], axis=1)
X_col = X.columns

In [7]:
y = df['Predictor']

In [8]:

#Savitzky-Golay filter with second degree derivative.
from scipy.signal import savgol_filter 

sg=savgol_filter(X,window_length=11, polyorder=3, deriv=2, delta=1.0)

C:\Users\akhil\Anaconda3\lib\site-packages\scipy\signal\_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]


In [9]:
sg_x=pd.DataFrame(sg, columns=X_col)
sg_x.head()

740       741       742       743       744       745       746  \
0  0.000084  0.000073  0.000061  0.000050  0.000039  0.000028  0.000010   
1  0.000033  0.000027  0.000021  0.000014  0.000008  0.000001 -0.000011   
2 -0.000139 -0.000128 -0.000117 -0.000105 -0.000094 -0.000082 -0.000078   
3  0.000055  0.000043  0.000031  0.000020  0.000008 -0.000004 -0.000022   
4 -0.000148 -0.000133 -0.000119 -0.000105 -0.000091 -0.000077 -0.000069   

        747       748       749    ...         1061      1062      1063  \
0 -0.000011 -0.000030 -0.000044    ...    -0.000446 -0.000474 -0.000300   
1 -0.000024 -0.000036 -0.000042    ...    -0.000446 -0.000474 -0.000300   
2 -0.000073 -0.000069 -0.000060    ...    -0.000462 -0.000491 -0.000310   
3 -0.000043 -0.000061 -0.000071    ...    -0.000471 -0.000502 -0.000315   
4 -0.000062 -0.000055 -0.000045    ...    -0.000446 -0.000473 -0.000299   

       1064      1065      1066      1067      1068      1069      1070  
0  0.000008  0.000319  0.000781  0.001243  0.001705  0.002167  0.002629  
1  0.000010  0.000322  0.000786  0.001250  0.001714  0.002178  0.002642  
2  0.000010  0.000334  0.000815  0.001296  0.001777  0.002258  0.002738  
3  0.000014  0.000347  0.000842  0.001337  0.001832  0.002327  0.002822  
4  0.000010  0.000322  0.000786  0.001249  0.001713  0.002176  0.002640  

[5 rows x 331 columns]

In [42]:
from sklearn.model_selection import train_test_split

In [52]:
X_train, X_test, y_train, y_test = train_test_split(sg_x, y,
                                                    train_size=0.8,
                                                    random_state=1,stratify = y)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [53]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=15)  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [54]:
pd.DataFrame(X_train).head()

0         1         2         3         4         5         6   \
0 -2.153120 -0.521615  2.096278 -2.653199  1.936347 -0.678512 -0.412160   
1  0.793335 -1.003247  1.585039 -1.576953  2.608780 -0.596795  0.404763   
2 -2.676651  1.118190 -1.208073 -0.834012  2.845332 -1.361971  5.017717   
3  4.645990  1.020540  0.324986 -0.524509 -4.293103 -4.497423 -2.569946   
4 -0.669729 -0.913898  3.121997  4.511966 -0.858567 -5.107973 -1.190666   

         7         8         9         10        11        12        13  \
0 -1.402645 -1.085823 -7.739414 -0.519025  0.241128  0.461290 -1.603855   
1 -0.644297 -1.725422 -2.419675  0.151759 -1.945308  0.933217 -0.819712   
2  2.590173 -2.602771  3.652716 -0.662136 -1.380277  1.560834 -0.603653   
3  4.879553  7.359028 -1.008641 -1.517124  1.426084  1.052501 -0.229407   
4 -2.237453  0.742981  2.355361  1.668705 -3.019222 -3.109874  0.075955   

         14  
0 -1.884483  
1  0.125786  
2 -0.636839  
3  1.473836  
4 -5.350234

In [55]:
from sklearn import svm
clf = svm.SVC(kernel="rbf")
clf.fit(X_train, y_train)  
y_pred = clf.predict(X_test)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [56]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred))) 

[[ 9  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  9  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  8  0  0  0  0  1  0  0  0  0  0  1  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0