In [1]:
import numpy as np
import pandas as pd

In [2]:
df =pd.read_csv("D:\\newproject\\New folder\\Chickpea.data.csv")

In [3]:
#Na Handling
df.isnull().values.any()

False

In [4]:
df=df.dropna()

In [5]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
X = df.drop(['Predictor'], axis=1)
X_col = X.columns

In [7]:
y = df['Predictor']

In [8]:

#Savitzky-Golay filter with second degree derivative.
from scipy.signal import savgol_filter 

sg=savgol_filter(X,window_length=11, polyorder=3, deriv=2, delta=1.0)

C:\Users\akhil\Anaconda3\lib\site-packages\scipy\signal\_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]


In [9]:
sg_x=pd.DataFrame(sg, columns=X_col)
sg_x.head()

740       741       742       743       744       745       746  \
0  0.000069  0.000062  0.000055  0.000048  0.000041  0.000035  0.000022   
1  0.000172  0.000149  0.000127  0.000104  0.000081  0.000059  0.000032   
2  0.000269  0.000236  0.000203  0.000170  0.000137  0.000104  0.000066   
3  0.000112  0.000099  0.000085  0.000072  0.000059  0.000045  0.000026   
4  0.000186  0.000161  0.000137  0.000112  0.000088  0.000063  0.000035   

        747       748       749    ...         1061      1062      1063  \
0  0.000006 -0.000009 -0.000020    ...    -0.000424 -0.000452 -0.000289   
1  0.000005 -0.000019 -0.000036    ...    -0.000416 -0.000442 -0.000284   
2  0.000027 -0.000009 -0.000036    ...    -0.000435 -0.000463 -0.000297   
3  0.000006 -0.000013 -0.000025    ...    -0.000449 -0.000478 -0.000304   
4  0.000007 -0.000018 -0.000035    ...    -0.000411 -0.000437 -0.000282   

           1064      1065      1066      1067      1068      1069      1070  
0  8.533263e-07  0.000294  0.000729  0.001164  0.001599  0.002034  0.002469  
1 -3.527249e-06  0.000280  0.000703  0.001125  0.001547  0.001969  0.002391  
2 -2.368324e-06  0.000296  0.000739  0.001182  0.001625  0.002069  0.002512  
3  5.485790e-06  0.000318  0.000783  0.001248  0.001713  0.002178  0.002643  
4 -7.838702e-06  0.000270  0.000682  0.001094  0.001506  0.001919  0.002331  

[5 rows x 331 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(sg_x, y,
                                                    train_size=0.8,
                                                    random_state=23,stratify = y)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [12]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=18)  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [15]:
from sklearn import svm
clf = svm.SVC(kernel="linear")
clf.fit(X_train, y_train)  
y_pred = clf.predict(X_test) 


In [16]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred))) 

[[10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  9  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  9  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  9  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0