In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("D:\\newproject\\New folder\\Sorghum.data.csv")

In [5]:
#Na Handling
df.isnull().values.any()

True

In [6]:
df=df.dropna()

In [7]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [8]:
X = df.drop(['Predictor'], axis=1)
X_col = X.columns

In [9]:
y = df['Predictor']

In [10]:

#Savitzky-Golay filter with second degree derivative.
from scipy.signal import savgol_filter 

sg=savgol_filter(X,window_length=11, polyorder=3, deriv=2, delta=1.0)

C:\Users\akhil\Anaconda3\lib\site-packages\scipy\signal\_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]


In [11]:
sg_x=pd.DataFrame(sg, columns=X_col)
sg_x.head()

740       741       742       743       744       745       746  \
0  0.000313  0.000282  0.000250  0.000218  0.000186  0.000154  0.000121   
1  0.000259  0.000235  0.000210  0.000185  0.000161  0.000136  0.000110   
2  0.000225  0.000203  0.000181  0.000158  0.000136  0.000114  0.000090   
3  0.000158  0.000150  0.000141  0.000133  0.000125  0.000117  0.000105   
4  0.000316  0.000287  0.000257  0.000228  0.000198  0.000169  0.000138   

        747       748           749    ...         1061      1062      1063  \
0  0.000079  0.000037  4.515035e-07    ...    -0.000507 -0.000523 -0.000332   
1  0.000071  0.000029 -7.377783e-06    ...    -0.000534 -0.000550 -0.000346   
2  0.000058  0.000023 -5.902443e-06    ...    -0.000508 -0.000524 -0.000334   
3  0.000078  0.000045  1.314993e-05    ...    -0.000520 -0.000536 -0.000336   
4  0.000096  0.000053  1.504493e-05    ...    -0.000507 -0.000522 -0.000331   

       1064      1065      1066      1067      1068      1069      1070  
0 -0.000003  0.000329  0.000805  0.001281  0.001757  0.002233  0.002709  
1  0.000004  0.000357  0.000864  0.001370  0.001877  0.002384  0.002890  
2 -0.000009  0.000321  0.000794  0.001266  0.001739  0.002211  0.002684  
3  0.000006  0.000351  0.000846  0.001341  0.001835  0.002330  0.002825  
4 -0.000004  0.000327  0.000801  0.001276  0.001750  0.002225  0.002699  

[5 rows x 331 columns]

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(sg)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(scaled_data, y,
                                                    train_size=0.8,
                                                    random_state=180,stratify = y)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [26]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=9)  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [27]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=5, random_state=42)

classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test) 

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [28]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred))) 

[[ 9  1  0  0  0  0  0  0  0  0]
 [ 1  8  1  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  9  0  1  0]
 [ 0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  1  9  0]
 [ 0  0  0  1  0  0  0  0  0  9]]
Accuracy0.94
